import type { Metadata } from "next";
import Navigation from "@components/RootLayout/Navigation/Navigation";
import TopMenu from "@components/RootLayout/TopMenu/TopMenu";

//@ts-ignore
import "./globals.scss";
import styles from "./app.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.appContainer}>
          <TopMenu />
          <div className={styles.mainContainer}>
            <Navigation />
            <div className={styles.contentContainer}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
